const moviesData = [
  {
    name: "Inception",
    popularity: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/qmDpIHrmpJINaRKAfWQfftjCdyi.jpg",
    rating: 4.5,
    description: "A mind-bending thriller where reality and dreams collide.",
    genre: "Sci-Fi",
    first_air_date: "2010-07-16",
    reviews: [],
  },
  {
    name: "The Dark Knight",
    popularity: 9.2,
    poster: "https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
    rating: 5,
    description: "A heroic and tragic tale of Gotham's dark protector.",
    genre: "Action",
    first_air_date: "2008-07-18",
    reviews: [],
  },
  {
    name: "The Godfather",
    popularity: 9.4,
    poster: "https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
    rating: 4.9,
    description: "The rise and fall of the Corleone family.",
    genre: "Drama",
    first_air_date: "1972-03-24",
    reviews: [],
  },
  {
    name: "Pulp Fiction",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/dM2w364MScsjFf8pfMbaWUcWrR.jpg",
    rating: 4.7,
    description: "An intertwining tale of violence and redemption.",
    genre: "Crime",
    first_air_date: "1994-10-14",
    reviews: [],
  },
  {
    name: "The Matrix",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg",
    rating: 4.8,
    description:
      "A hacker discovers a mind-bending reality where humanity is enslaved by machines.",
    genre: "Sci-Fi",
    first_air_date: "1999-03-31",
    reviews: [],
  },
  {
    name: "Gladiator",
    popularity: 9.1,
    poster: "https://image.tmdb.org/t/p/w500/ty8TGRuvJLPUmAR1H1nRIsgwvim.jpg",
    rating: 4.7,
    description:
      "A former Roman General seeks revenge against the corrupt emperor who murdered his family.",
    genre: "Action",
    first_air_date: "2000-05-01",
    reviews: [],
  },
  {
    name: "Titanic",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/zNDTzibnIGBGpMhs4ox50uO27RA.jpg",
    rating: 4.6,
    description:
      "A romantic tale set against the ill-fated voyage of the Titanic.",
    genre: "Romance",
    first_air_date: "1997-12-19",
    reviews: [],
  },
  {
    name: "Jurassic Park",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/9i3plLl89DHMz7mahksDaAo7HIS.jpg",
    rating: 4.3,
    description: "A theme park populated by cloned dinosaurs faces disaster.",
    genre: "Sci-Fi",
    first_air_date: "1993-06-11",
    reviews: [],
  },
  {
    name: "The Shawshank Redemption",
    popularity: 9.3,
    poster: "https://image.tmdb.org/t/p/w500/q6y0Go1tsGEsmtFryDOJo3dEmqu.jpg",
    rating: 4.9,
    description:
      "A man is wrongly imprisoned for murder and forms a friendship with a fellow inmate.",
    genre: "Drama",
    first_air_date: "1994-09-23",
    reviews: [],
  },
  {
    name: "Fight Club",
    popularity: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/bptfVGEQuv6vDTIMVCHjJ9Dz8PX.jpg",
    rating: 4.6,
    description:
      "An underground fight club evolves into something much darker.",
    genre: "Thriller",
    first_air_date: "1999-10-15",
    reviews: [],
  },
  {
    name: "Interstellar",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/rAiYTfKGqDCRIIqo664sY9XZIvQ.jpg",
    rating: 4.7,
    description:
      "A team of explorers travel through a wormhole in search of a new habitable planet.",
    genre: "Sci-Fi",
    first_air_date: "2014-11-07",
    reviews: [],
  },
  {
    name: "Braveheart",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/or1gBugydmjToAEq7OZY0owwFk.jpg",
    rating: 4.5,
    description:
      "A Scottish warrior leads a rebellion to free his homeland from English tyranny.",
    genre: "Action",
    first_air_date: "1995-05-24",
    reviews: [],
  },
  {
    name: "Forrest Gump",
    popularity: 9.1,
    poster: "https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg",
    rating: 4.8,
    description:
      "The life story of a man with a kind heart who experiences key events in American history.",
    genre: "Drama",
    first_air_date: "1994-07-06",
    reviews: [],
  },
  {
    name: "Avatar",
    popularity: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/kmcqlZGaSh20zpTbuoF0Cdn07dT.jpg",
    rating: 4.5,
    description:
      "A paraplegic marine is sent to the moon Pandora and becomes part of the planet's native population.",
    genre: "Sci-Fi",
    first_air_date: "2009-12-18",
    reviews: [],
  },
  {
    name: "Mad Max: Fury Road",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/kqjL17yufvn9OVLyXYpvtyrFfak.jpg",
    rating: 4.7,
    description:
      "In a post-apocalyptic world, Max teams up with a mysterious woman to flee from a tyrannical warlord.",
    genre: "Action",
    first_air_date: "2015-05-15",
    reviews: [],
  },
  {
    name: "The Silence of the Lambs",
    popularity: 9.2,
    poster: "https://image.tmdb.org/t/p/w500/rplLJ2hPcOQmkFhTqUte0MkEaO2.jpg",
    rating: 4.9,
    description:
      "A young FBI cadet must confide in an imprisoned killer to catch another serial killer.",
    genre: "Thriller",
    first_air_date: "1991-02-14",
    reviews: [],
  },
  {
    name: "The Lion King",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/sKCr78MXSLixwmZ8DyJLrpMsd15.jpg",
    rating: 4.8,
    description:
      "A young lion prince flees from his kingdom after the death of his father, only to return later.",
    genre: "Adventure",
    first_air_date: "1994-06-15",
    reviews: [],
  },
  {
    name: "Django Unchained",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/7oWY8VDWW7thTzWh3OKYRkWUlD5.jpg",
    rating: 4.7,
    description:
      "A freed slave sets out to rescue his wife from a brutal plantation owner.",
    genre: "Action",
    first_air_date: "2012-12-25",
    reviews: [],
  },
  {
    name: "The Departed",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/jyAgiqVSx5fl0NNj7WoGGKweXrL.jpg",
    rating: 4.6,
    description:
      "An undercover cop and a mole in the police force try to identify each other.",
    genre: "Crime",
    first_air_date: "2006-10-06",
    reviews: [],
  },
  {
    name: "Whiplash",
    popularity: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/lIv1QinFqz4dlp5U4lQ6HaiskOZ.jpg",
    rating: 4.5,
    description:
      "A young drummer enrolls in a prestigious music school and faces harsh training from an abusive teacher.",
    genre: "Drama",
    first_air_date: "2014-10-10",
    reviews: [],
  },
  {
    name: "The Avengers",
    popularity: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
    rating: 4.8,
    description:
      "Earth's mightiest heroes must come together to stop a powerful enemy from destroying the planet.",
    genre: "Action",
    first_air_date: "2012-05-04",
    reviews: [],
  },
  {
    name: "The Wolf of Wall Street",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/sOxr33wnRuKazR9ClHek73T8qnK.jpg",
    rating: 4.6,
    description:
      "The rise and fall of a corrupt stockbroker, who exploits Wall Street to amass a fortune.",
    genre: "Crime",
    first_air_date: "2013-12-25",
    reviews: [],
  },
  {
    name: "Joker",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/udDclJoHjfjb8Ekgsd4FDteOkCU.jpg",
    rating: 4.7,
    description:
      "A failed comedian descends into madness and becomes the infamous Joker.",
    genre: "Crime",
    first_air_date: "2019-10-04",
    reviews: [],
  },
  {
    name: "The Prestige",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/5MXyQfz8xUP3dIFPTubhTsbFY6N.jpg",
    rating: 4.6,
    description:
      "Two stage magicians engage in a rivalry that leads them to dangerous lengths.",
    genre: "Drama",
    first_air_date: "2006-10-20",
    reviews: [],
  },

  {
    name: "The Green Mile",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/sOHqdY1RnSn6kcfAHKu28jvTebE.jpg",
    rating: 4.8,
    description:
      "A death row prison guard forms a bond with a man who possesses a mysterious gift.",
    genre: "Drama",
    first_air_date: "1999-12-10",
    reviews: [],
  },
  {
    name: "Star Wars: Episode IV - A New Hope",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/6FfCtAuVAW8XJjZ7eWeLibRLWTw.jpg",
    rating: 4.7,
    description:
      "A young farm boy becomes a Jedi and joins the Rebellion to take down the Empire.",
    genre: "Sci-Fi",
    first_air_date: "1977-05-25",
    reviews: [],
  },
  {
    name: "The Lord of the Rings: The Fellowship of the Ring",
    popularity: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/56zTpe2xvaA4alU51sRWPoKPYZy.jpg",
    rating: 4.9,
    description:
      "A hobbit embarks on a journey to destroy a powerful ring and save Middle-earth.",
    genre: "Fantasy",
    first_air_date: "2001-12-19",
    reviews: [],
  },
  {
    name: "The Social Network",
    popularity: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/n0ybibhJtQ5icDqTp8eRytcIHJx.jpg",
    rating: 4.6,
    description:
      "The founding of Facebook and the legal battles that followed.",
    genre: "Drama",
    first_air_date: "2010-10-01",
    reviews: [],
  },
  {
    name: "Goodfellas",
    popularity: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/qb4l6oDNKMSR0JfPDb1nxm0Ot8N.jpg",
    rating: 4.8,
    description:
      "The story of a mob associate rising through the ranks of organized crime.",
    genre: "Crime",
    first_air_date: "1990-09-12",
    reviews: [],
  },
  {
    name: "Schindler's List",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/c8Ass7acuOe4za6DhSattE359gr.jpg",
    rating: 4.9,
    description: "A businessman saves thousands of Jews during the Holocaust.",
    genre: "Drama",
    first_air_date: "1993-12-15",
    reviews: [],
  },
  {
    name: "The Terminator",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/qKkFk9HELmABpcPoc1HHZGIxQ5a.jpg",
    rating: 4.4,
    description:
      "A cyborg is sent from the future to kill the mother of the future resistance leader.",
    genre: "Sci-Fi",
    first_air_date: "1984-10-26",
    reviews: [],
  },
  {
    name: "Se7en",
    popularity: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/69Sns8WoET6CfaYlIkHbla4l7nC.jpg",
    rating: 4.8,
    description:
      "Two detectives hunt a serial killer who uses the seven deadly sins as his modus operandi.",
    genre: "Thriller",
    first_air_date: "1995-09-22",
    reviews: [],
  },
  {
    name: "Alien",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/2v9FVVBUrry9S0tX4VjQtz8KBk0.jpg",
    rating: 4.7,
    description:
      "A space crew encounters a deadly alien organism after investigating a distress signal.",
    genre: "Sci-Fi",
    first_air_date: "1979-05-25",
    reviews: [],
  },
  {
    name: "The Grand Budapest Hotel",
    popularity: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/kwYt1KikGgKqmDvtph0hINtT95.jpg",
    rating: 4.6,
    description:
      "A concierge teams up with a lobby boy to prove his innocence after being framed for murder.",
    genre: "Comedy",
    first_air_date: "2014-03-28",
    reviews: [],
  },
  {
    name: "12 Angry Men",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/3W0v956XxSG5xgm7LB6qu8ExYJ2.jpg",
    rating: 4.9,
    description:
      "A jury must decide the fate of a young man accused of murder.",
    genre: "Drama",
    first_air_date: "1957-04-10",
    reviews: [],
  },
  {
    name: "Saving Private Ryan",
    popularity: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/jCq9Y9AMTu4tSwhGP5egIikxR4M.jpg",
    rating: 4.7,
    description:
      "A group of soldiers are sent on a mission to rescue a paratrooper behind enemy lines.",
    genre: "Action",
    first_air_date: "1998-07-24",
    reviews: [],
  },
  {
    name: "The Sixth Sense",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/fIssD3w3SvIhPPmVo4WMgZDVLID.jpg",
    rating: 4.7,
    description:
      "A young boy can see and communicate with dead people, leading a psychologist to help him.",
    genre: "Thriller",
    first_air_date: "1999-08-06",
    reviews: [],
  },
  {
    name: "Gone Girl",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/qymaJhucquUwjpb8oiqynMeXnID.jpg",
    rating: 4.5,
    description:
      "A man becomes the prime suspect in the disappearance of his wife.",
    genre: "Thriller",
    first_air_date: "2014-10-03",
    reviews: [],
  },
  {
    name: "Black Swan",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/hMVMMy1yDUeaSki8b2FrfksnVjM.jpg",
    rating: 4.6,
    description:
      "A ballet dancer descends into madness as she prepares for a role in Swan Lake.",
    genre: "Drama",
    first_air_date: "2010-12-17",
    reviews: [],
  },
  {
    name: "Requiem for a Dream",
    popularity: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/nOd6vjEmzCT0k4VYqsA2hwyi87C.jpg",
    rating: 4.6,
    description:
      "The story of four people spiraling into addiction and despair.",
    genre: "Drama",
    first_air_date: "2000-10-27",
    reviews: [],
  },
  {
    name: "Inglourious Basterds",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/7sfbEnaARXDDhKm0CZ7D7uc2sbo.jpg",
    rating: 4.7,
    description:
      "A group of Jewish-American soldiers plot to assassinate Nazi leaders in World War II.",
    genre: "Action",
    first_air_date: "2009-08-21",
    reviews: [],
  },
  {
    name: "Shutter Island",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/kve20tXwUZpu4GUX8l6X7Z4jmL6.jpg",
    rating: 4.8,
    description:
      "A U.S. Marshal investigates a mental institution on a mysterious island.",
    genre: "Thriller",
    first_air_date: "2010-02-19",
    reviews: [],
  },
  {
    name: "A Beautiful Mind",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/zwzWCmH72OSC9NA0ipoqw5Zjya8.jpg",
    rating: 4.8,
    description: "A brilliant mathematician grapples with schizophrenia.",
    genre: "Drama",
    first_air_date: "2001-12-13",
    reviews: [],
  },
  {
    name: "The Imitation Game",
    popularity: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/zSqJ1qFq8NXFfi7JeIYMlzyR0dx.jpg",
    rating: 4.6,
    description: "The story of Alan Turing, who cracked the Nazi Enigma code.",
    genre: "Drama",
    first_air_date: "2014-11-14",
    reviews: [],
  },
  {
    name: "Deadpool",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/inVq3FRqcYIRl2la8iZikYYxFNR.jpg",
    rating: 4.7,
    description:
      "A former special forces operative turns into a wisecracking anti-hero.",
    genre: "Action",
    first_air_date: "2016-02-12",
    reviews: [],
  },
  {
    name: "Guardians of the Galaxy",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg",
    rating: 4.6,
    description:
      "A group of intergalactic criminals must pull together to stop a fanatical warrior.",
    genre: "Action",
    first_air_date: "2014-08-01",
    reviews: [],
  },
  {
    name: "The Pursuit of Happyness",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/f6ZDI2LZ70IPtnzdm4mAxMRfX8t.jpg",
    rating: 4.8,
    description:
      "A struggling salesman takes custody of his son as he fights for a better life.",
    genre: "Drama",
    first_air_date: "2006-12-15",
    reviews: [],
  },
  {
    name: "The Truman Show",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/lHbHTjcrNQXaIU2lIXFChgFH1W.jpg",
    rating: 4.7,
    description: "A man discovers his entire life is a reality TV show.",
    genre: "Comedy",
    first_air_date: "1998-06-05",
    reviews: [],
  },

  {
    name: "The Dark Knight Rises",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/hr0LxiI0Nd8l3RPuWWYsXfFi7ht.jpg",
    rating: 4.7,
    description: "Batman returns to Gotham to face a new threat from Bane.",
    genre: "Action",
    first_air_date: "2012-07-20",
    reviews: [],
  },
  {
    name: "Iron Man",
    popularity: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/78lPtwv72eTNqFW9COBYI0dWDJa.jpg",
    rating: 4.6,
    description:
      "A billionaire industrialist builds a powered suit of armor to save his life and fight crime.",
    genre: "Action",
    first_air_date: "2008-05-02",
    reviews: [],
  },
  {
    name: "Thor: Ragnarok",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/rzRwTcFvttcN1ZpX2xv4j3tSdJu.jpg",
    rating: 4.6,
    description:
      "Thor must escape the alien planet Sakaar to stop Hela from destroying Asgard.",
    genre: "Action",
    first_air_date: "2017-11-03",
    reviews: [],
  },
  {
    name: "Coco",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/eKi8dIrr8voobbaGzDpe8w0PVbC.jpg",
    rating: 4.8,
    description:
      "A young boy embarks on a journey to the Land of the Dead to discover his family's history.",
    genre: "Animation",
    first_air_date: "2017-11-22",
    reviews: [],
  },
  {
    name: "Inside Out",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg",
    rating: 4.7,
    description:
      "The emotions inside a young girl’s mind navigate her life as she deals with growing up.",
    genre: "Animation",
    first_air_date: "2015-06-19",
    reviews: [],
  },
  {
    name: "Spider-Man: Into the Spider-Verse",
    popularity: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/iiZZdoQBEYBv6id8su7ImL0oCbD.jpg",
    rating: 4.9,
    description:
      "Teenager Miles Morales becomes the Spider-Man of his reality and teams up with other Spider-People.",
    genre: "Animation",
    first_air_date: "2018-12-14",
    reviews: [],
  },
  {
    name: "Finding Nemo",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/eHuGQ10FUzK1mdOY69wF5pGgEf5.jpg",
    rating: 4.6,
    description: "A clownfish embarks on a journey to find his lost son.",
    genre: "Animation",
    first_air_date: "2003-05-30",
    reviews: [],
  },
  {
    name: "The Incredibles",
    popularity: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/2LqaLgk4Z226KkgPJuiOQ58wvrm.jpg",
    rating: 4.7,
    description:
      "A family of superheroes come out of retirement to save the world.",
    genre: "Animation",
    first_air_date: "2004-11-05",
    reviews: [],
  },
  {
    name: "Toy Story",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/uXDfjJbdP4ijW5hWSBrPrlKpxab.jpg",
    rating: 4.8,
    description:
      "A cowboy doll tries to protect his position as the favorite toy when a space ranger arrives.",
    genre: "Animation",
    first_air_date: "1995-11-22",
    reviews: [],
  },
  {
    name: "Frozen",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/1NnNg2vStDq1Tow0BYLStQ5MWVn.jpg",
    rating: 4.6,
    description:
      "A young queen must embrace her magical powers to save her kingdom from eternal winter.",
    genre: "Animation",
    first_air_date: "2013-11-27",
    reviews: [],
  },
  {
    name: "Moana",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/d9jZPwN2fgkWL4C8zHcoSLoRthI.jpg",
    rating: 4.7,
    description:
      "A spirited teenager embarks on a quest to save her people, guided by the demigod Maui.",
    genre: "Animation",
    first_air_date: "2016-11-23",
    reviews: [],
  },
  {
    name: "Shrek",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/iB64vpL3dIObOtMZgX3RqdVdQDc.jpg",
    rating: 4.6,
    description:
      "An ogre embarks on a quest to rescue a princess and ends up befriending a talking donkey.",
    genre: "Animation",
    first_air_date: "2001-05-18",
    reviews: [],
  },
  {
    name: "Despicable Me",
    popularity: 8.0,
    poster: "https://image.tmdb.org/t/p/w500/4zHJhBSY4kNZXfhTlmy2TzXD51M.jpg",
    rating: 4.5,
    description:
      "A supervillain adopts three orphan girls as part of his grand evil plan, but grows attached to them.",
    genre: "Animation",
    first_air_date: "2010-07-09",
    reviews: [],
  },
  {
    name: "Monsters, Inc.",
    popularity: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/sgheSKxZkttIe8ONsf2sWXPgip3.jpg",
    rating: 4.6,
    description:
      "Two monsters must return a human child back to her world before it's too late.",
    genre: "Animation",
    first_air_date: "2001-11-02",
    reviews: [],
  },
  {
    name: "Zootopia",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/sM33SANp9z6rXW8Itn7NnG1GOEs.jpg",
    rating: 4.7,
    description:
      "A rookie bunny cop and a cynical fox con artist work together to uncover a conspiracy.",
    genre: "Animation",
    first_air_date: "2016-03-04",
    reviews: [],
  },
  {
    name: "Ratatouille",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/cxPIA3nOQfoVwB6f3UlvPDPpE2Y.jpg",
    rating: 4.8,
    description:
      "A rat who can cook makes an unusual alliance with a young kitchen worker at a famous restaurant.",
    genre: "Animation",
    first_air_date: "2007-06-29",
    reviews: [],
  },
  {
    name: "Up",
    popularity: 8.9,
    poster: "https://image.tmdb.org/t/p/w500/sVpziO87NUs85g3ubytVS9P52Ge.jpg",
    rating: 4.9,
    description:
      "An elderly widower and a young boy set out on an adventure in a flying house.",
    genre: "Animation",
    first_air_date: "2009-05-29",
    reviews: [],
  },
  {
    name: "Harry Potter and the Sorcerer's Stone",
    popularity: 9.0,
    poster: "https://image.tmdb.org/t/p/w500/uC6TTUhPpQCmgldGyYveKRAu8JN.jpg",
    rating: 4.8,
    description:
      "A young boy discovers he is a wizard and begins his journey at Hogwarts.",
    genre: "Fantasy",
    first_air_date: "2001-11-16",
    reviews: [],
  },
  {
    name: "The Hobbit: An Unexpected Journey",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/xrI4EnZWftpo1B7tTvlMUXVOikd.jpg",
    rating: 4.5,
    description: "A hobbit is swept into a quest to reclaim a lost kingdom.",
    genre: "Fantasy",
    first_air_date: "2012-12-14",
    reviews: [],
  },
  {
    name: "Pirates of the Caribbean: The Curse of the Black Pearl",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg",
    rating: 4.7,
    description:
      "A pirate teams up with a blacksmith to rescue a kidnapped woman and defeat an undead crew.",
    genre: "Adventure",
    first_air_date: "2003-07-09",
    reviews: [],
  },
  {
    name: "The Chronicles of Narnia: The Lion, the Witch and the Wardrobe",
    popularity: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/iREd0rNCjYdf5Ar0vfaW32yrkm.jpg",
    rating: 4.6,
    description:
      "Four children enter a magical world ruled by an evil witch and must help the lion Aslan save it.",
    genre: "Fantasy",
    first_air_date: "2005-12-09",
    reviews: [],
  },
  {
    name: "Aladdin",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/3iLPrkLuyR6vGWDYC7pXxKUyXEz.jpg",
    rating: 4.8,
    description:
      "A street rat discovers a magical lamp and uses the genie's powers to win the love of a princess.",
    genre: "Fantasy",
    first_air_date: "1992-11-25",
    reviews: [],
  },
  {
    name: "The Princess Bride",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/kcvz3O6GbMnp6uvJrJd3uYZPmY1.jpg",
    rating: 4.7,
    description: "A farmhand must rescue his true love from an evil prince.",
    genre: "Fantasy",
    first_air_date: "1987-09-25",
    reviews: [],
  },
  {
    name: "Beauty and the Beast",
    popularity: 8.5,
    poster: "https://image.tmdb.org/t/p/w500/tWqifoYuwLETmmasnGHO7xBjEtt.jpg",
    rating: 4.6,
    description:
      "A young woman falls in love with a cursed prince living in an enchanted castle.",
    genre: "Fantasy",
    first_air_date: "2017-03-17",
    reviews: [],
  },
  {
    name: "The Lord of the Rings: The Two Towers",
    popularity: 9.1,
    poster: "https://image.tmdb.org/t/p/w500/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
    rating: 4.9,
    description:
      "The Fellowship is broken but continues its quest to destroy the One Ring.",
    genre: "Fantasy",
    first_air_date: "2002-12-18",
    reviews: [],
  },
  {
    name: "The Hunger Games",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/iQK0pkJwCPlhTCOl6pPzQW0qSeR.jpg",
    rating: 4.7,
    description:
      "A girl must compete in a brutal survival competition where only one person can live.",
    genre: "Adventure",
    first_air_date: "2012-03-23",
    reviews: [],
  },
  {
    name: "The Jungle Book",
    popularity: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/tOgtE1pDqHuZAloRHmSrHCBiJXz.jpg",
    rating: 4.5,
    description:
      "A young boy raised by wolves embarks on an adventure to escape a man-eating tiger.",
    genre: "Adventure",
    first_air_date: "2016-04-15",
    reviews: [],
  },
  {
    name: "Wonder Woman",
    popularity: 8.6,
    poster: "https://image.tmdb.org/t/p/w500/gfJGlDaHuWimErCr5Ql0I8x9QSy.jpg",
    rating: 4.8,
    description:
      "An Amazon princess leaves her island to fight alongside humans in a war to end all wars.",
    genre: "Fantasy",
    first_air_date: "2017-06-02",
    reviews: [],
  },
  {
    name: "Tangled",
    popularity: 8.7,
    poster: "https://image.tmdb.org/t/p/w500/ym7Kst6a4uodryxqbGOxmewF235.jpg",
    rating: 4.7,
    description:
      "A young woman with magical long hair escapes from her tower with the help of a thief.",
    genre: "Romance",
    first_air_date: "2010-11-24",
    reviews: [],
  },
  {
    name: "The Twilight Saga: Breaking Dawn - Part 2",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/jHE7WUfBhYOzBXRwKBMuzk9EZ6L.jpg",
    rating: 4.4,
    description:
      "Bella and Edward face new challenges as they raise their daughter in the vampire world.",
    genre: "Romance",
    first_air_date: "2012-11-16",
    reviews: [],
  },
  {
    name: "The Shape of Water",
    popularity: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/iLYLADGA5oKGM92Ns1j9CDgk3iI.jpg",
    rating: 4.5,
    description:
      "A mute woman falls in love with an amphibious creature held in captivity at a government lab.",
    genre: "Romance",
    first_air_date: "2017-12-01",
    reviews: [],
  },
  {
    name: "La La Land",
    popularity: 8.8,
    poster: "https://image.tmdb.org/t/p/w500/uDO8zWDhfWwoFdKS4fzkUJt0Rf0.jpg",
    rating: 4.8,
    description:
      "A jazz musician and an aspiring actress fall in love but must balance their dreams with reality.",
    genre: "Romance",
    first_air_date: "2016-12-09",
    reviews: [],
  },
  {
    name: "Enchanted",
    popularity: 7.9,
    poster: "https://image.tmdb.org/t/p/w500/8K9xIBsBfVW6nT1jRfNNrljdKmW.jpg",
    rating: 4.4,
    description:
      "A fairytale princess is thrust into the real world and falls in love with a lawyer.",
    genre: "Romance",
    first_air_date: "2007-11-21",
    reviews: [],
  },
  {
    name: "The Fault in Our Stars",
    popularity: 8.3,
    poster: "https://image.tmdb.org/t/p/w500/cldfqfTHPYPjgQpnwJfmn3fnizW.jpg",
    rating: 4.7,
    description:
      "Two teenagers with cancer form a deep connection and experience the trials of love and loss.",
    genre: "Romance",
    first_air_date: "2014-06-06",
    reviews: [],
  },
  {
    name: "Alita: Battle Angel",
    popularity: 8.1,
    poster: "https://image.tmdb.org/t/p/w500/xRWht48C2V8XNfzvPehyClOvDni.jpg",
    rating: 4.6,
    description:
      "A cyborg girl fights to uncover her past and protect her future in a dystopian world.",
    genre: "Adventure",
    first_air_date: "2019-02-14",
    reviews: [],
  },
  {
    name: "Jumanji: Welcome to the Jungle",
    popularity: 8.2,
    poster: "https://image.tmdb.org/t/p/w500/bXrZ5iHBEjH7WMidbUDQ0U2xbmr.jpg",
    rating: 4.5,
    description:
      "Four teenagers are sucked into a magical video game and must survive in the jungle.",
    genre: "Adventure",
    first_air_date: "2017-12-20",
    reviews: [],
  },
  {
    name: "Maleficent",
    popularity: 8.4,
    poster: "https://image.tmdb.org/t/p/w500/ik8PugpL41s137RAWEGTAWu0dPo.jpg",
    rating: 4.7,
    description:
      "A vengeful fairy curses an infant princess, only to realize she may be the child's true protector.",
    genre: "Fantasy",
    first_air_date: "2014-05-30",
    reviews: [],
  },
];
module.exports=moviesData